### ISSUE TITLE
Test MorphoDepot prototype

### ISSUE THREAD

**Issue by pieper** [pieper/MD_E15#7]
This is just a test issue so that you can try the prototype module.  You can try segmenting something if you want, or just submit a PR with a blank segmentation.

The instructions for using the module are here: [https://github.com/pieper/MorphoDepotDocs/blob/main/Segmenter.md](https://github.com/pieper/MorphoDepotDocs/blob/main/Segmenter.md)

And for reference the instructions for PIs are here: [https://github.com/pieper/MorphoDepotDocs/blob/main/PI.md](https://github.com/pieper/MorphoDepotDocs/blob/main/PI.md).

**Comment by muratmaga** [comment]
got stuck at "refresh". Not executing the `gh`

```
Traceback (most recent call last):
  File "/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 152, in updateIssueList
    issueList = self.logic.issueList()
  File "/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 255, in issueList
    issueList = json.loads(self.gh("search issues --assignee=@me --state open --json repository,title,number"))
  File "/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 246, in gh
    process = slicer.util.launchConsoleProcess(["gh"] + command.split())
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 3778, in launchConsoleProcess
    proc = subprocess.Popen(args, env=startupEnv, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True, cwd=cwd)
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gh'
```

**Comment by muratmaga** [comment]
ok, hardcoding the "gh" as "/opt/homebrew/bin/gh" overcame this problem. Not sure why it is not finding the brew path though...

**Comment by muratmaga** [comment]
But I am not seeing this issue being listed as my assigned issue:
![image](https://github.com/user-attachments/assets/f66afd60-c21b-4f12-8c71-e56ddec5e9e6)

**Comment by muratmaga** [comment]
Ok. That was simple. You did not assign the issue to me :)

**Comment by pieper** [comment]
> Ok. That was simple. You did not assign the issue to me :)

Right - I couldn't do that until you are a collaborator on the project : )

**Comment by muratmaga** [comment]
Some more observations and data points. GH has the same issue on windows (i.e., if I invoke Slicer from the icon, it is not found). Starting it from the terminal or power shell solves the problem, but it is not how most people uses. 

This time on windows I encountered an error when I click on the Save Checkpoint. Below is the output from python console:
```
Python 3.9.10 (main, Apr  5 2024, 01:02:26) [MSC v.1938 64 bit (AMD64)] on win32
>>> 
[Qt] libpng warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
[Qt] libpng warning: iCCP: known incorrect sRGB profile
('[{"number":7,"repository":{"name":"MD_E15","nameWithOwner":"pieper/MD_E15"},"title":"Test MorphoDepot prototype"},{"number":46,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Screen resolution limitation in xfce4 "},{"number":45,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Missing packages to support R/devtools"},{"number":44,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Better openGl performance in CPU nodes"},{"number":31,"repository":{"name":"Morphology-analysis","nameWithOwner":"hdr-bgnn/Morphology-analysis"},"title":"color legend"}]\n', None)
('[{"name":"MD_E15"},{"name":"MorphoCloudWorkflow"},{"name":"fake_tutorial"},{"name":"MorphoCloudPortal"},{"name":"SlicerMorphR"},{"name":"Slicer"},{"name":"exosphere"},{"name":"pyRserve"},{"name":"nnmouse"},{"name":"scanner_stuff"},{"name":"mouse_CT_atlas"},{"name":"SlicerMorph_Rexamples"},{"name":"MONAILabel"},{"name":"Tutorials"},{"name":"demo"},{"name":"scanner_logs"},{"name":"dummy"},{"name":"ProjectWeek"},{"name":"fatih"},{"name":"rtd-tutorial"},{"name":"SlicerMorph"},{"name":"terms"},{"name":"blog"},{"name":"Scripts"},{"name":"test_images"},{"name":"bgnn_related"},{"name":"MMLLM"},{"name":"monai-deepedit"},{"name":"VolImportModule"},{"name":"SampleData"}]\n', None)
("Cloning into 'C:/Users/amaga/Documents/MD_E15'...\nFrom https://github.com/pieper/MD_E15\n * [new branch]      main       -> upstream/main\n", None)
https://github.com/SlicerMorph/SampleData/raw/refs/heads/master/IMPC_sample_data.nrrd
[Qt] QLayout::addChildLayout: layout "" already has a parent
[Qt] ctkSliderWidget::setSingleStep()  0 is out of bounds. 0 100 1
[VTK] DeserializeImageGeometry: Failed to de-serialize geometry string 
issueCheckpoint
Traceback (most recent call last):
  File "C:/Users/amaga/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 346, in issueCheckpoint
    self.localRepo.index.add([self.segmentationPath])
  File "C:\Users\amaga\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\site-packages\git\index\base.py", line 803, in add
    paths, entries = self._preprocess_add_items(items)
  File "C:\Users\amaga\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\site-packages\git\index\base.py", line 620, in _preprocess_add_items
    paths.append(self._to_relative_path(item))
  File "C:\Users\amaga\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\site-packages\git\index\base.py", line 605, in _to_relative_path
    raise ValueError("Absolute path %r is not in git repository at %r" % (path, self.repo.working_tree_dir))
ValueError: Absolute path 'C:/Users/amaga/Documents/MD_E15/issue-7.seg.nrrd' is not in git repository at 'C:\\Users\\amaga\\Documents\\MD_E15'
```

**Comment by pieper** [comment]
These windows and mac issues all be solvable but let's get the basics working first on jetstream so we get a feel for how workable the system is.

**Comment by muratmaga** [comment]
ok. I will try on JS2 instance.

**Comment by pieper** [comment]
BTW, let's put issues about the module itself in https://github.com/pieper/SlicerMorphoDepot/issues.  I'll add one about win/mac and point back to this.
